import type { PlaneCommand } from './lab.ts';

export function exportPlaneRegression(recipe: readonly PlaneCommand[]) {
  const start = recipe.findIndex((command) => command.type === 'start_crawl');
  const finish = recipe.findIndex(
    (command, index) => index > start && command.type === 'release',
  );
  const edit = recipe.find(
    (command, index) =>
      index > start &&
      (finish < 0 || index < finish) &&
      command.type === 'edit_metadata',
  );
  if (start < 0 || finish < 0 || !edit || edit.type !== 'edit_metadata')
    throw new Error(
      'Export needs a queued crawl, a later metadata edit, and worker completion.',
    );
  return `// Generated by Interleave from Plane issue makeplane/plane#9674.
// Pinned source: preview@da1a7ab85012d16836459a10dd92ec55eb739c69.
// Default = proposed compare-and-set patch. Set INTERLEAVE_IMPLEMENTATION=unguarded
// to prove this test catches Plane's current unconditional worker write.
// Standalone: node --test interleave-plane-regression.test.mjs
import test from 'node:test';
import assert from 'node:assert/strict';

const recipe = ${JSON.stringify(recipe, null, 2)};
const expectedMetadataTitle = ${JSON.stringify(edit.title)};
const mode = process.env.INTERLEAVE_IMPLEMENTATION === 'unguarded'
  ? 'unguarded'
  : 'guarded';

function deferred() {
  let resolve;
  const promise = new Promise((done) => { resolve = done; });
  return { promise, resolve };
}

async function replayPlane(commands, implementation) {
  const link = {
    displayTitle: 'Incident response',
    metadataTitle: 'Plane documentation',
    revision: 0,
  };
  let checkpoint = null;
  let worker = null;
  let completion = null;

  for (const command of commands) {
    if (command.type === 'observe') continue;
    if (command.type === 'start_crawl') {
      assert.equal(worker, null, 'Only one crawl may be pending.');
      link.displayTitle = command.title;
      link.revision += 1;
      const queuedRevision = link.revision;
      checkpoint = deferred();
      worker = (async () => {
        await checkpoint.promise;
        if (
          implementation === 'guarded' &&
          link.revision !== queuedRevision
        ) {
          completion = 'blocked';
          return;
        }
        link.metadataTitle = 'Plane documentation';
        link.revision += 1;
        completion = 'applied';
      })();
      continue;
    }
    if (command.type === 'edit_metadata') {
      link.metadataTitle = command.title;
      link.revision += 1;
      continue;
    }
    if (command.type === 'release') {
      assert.ok(checkpoint && worker, 'The crawl must be queued first.');
      checkpoint.resolve();
      await worker;
      checkpoint = null;
      worker = null;
      continue;
    }
    throw new Error(\`Unsupported command: \${command.type}\`);
  }

  assert.equal(worker, null, 'The recording ended with pending work.');
  const passed = link.metadataTitle === expectedMetadataTitle;
  return {
    link,
    completion,
    passed,
    message: passed
      ? 'The stale crawl was blocked and the human edit survived.'
      : 'The stale crawl overwrote the newer human edit.',
  };
}

test('a queued Plane crawl cannot overwrite a newer explicit metadata edit', async () => {
  const result = await replayPlane(recipe, mode);
  assert.equal(result.passed, true, result.message);
  assert.equal(result.link.metadataTitle, expectedMetadataTitle);
  assert.equal(result.completion, 'blocked');
});
`;
}

export const PLANE_UPSTREAM_PATCH = `diff --git a/apps/api/plane/app/views/issue/link.py b/apps/api/plane/app/views/issue/link.py
--- a/apps/api/plane/app/views/issue/link.py
+++ b/apps/api/plane/app/views/issue/link.py
@@
-            crawl_work_item_link_title.delay(serializer.data.get("id"), serializer.data.get("url"))
+            crawl_work_item_link_title.delay(
+                serializer.data.get("id"),
+                serializer.data.get("url"),
+                serializer.instance.updated_at.isoformat(),
+            )
@@
-            serializer.save()
-            crawl_work_item_link_title.delay(serializer.data.get("id"), serializer.data.get("url"))
+            url_changed = "url" in serializer.validated_data and serializer.validated_data["url"] != issue_link.url
+            metadata_supplied = "metadata" in serializer.validated_data
+            serializer.save()
+            if url_changed and not metadata_supplied:
+                crawl_work_item_link_title.delay(
+                    serializer.data.get("id"),
+                    serializer.data.get("url"),
+                    serializer.instance.updated_at.isoformat(),
+                )
diff --git a/apps/api/plane/bgtasks/work_item_link_task.py b/apps/api/plane/bgtasks/work_item_link_task.py
--- a/apps/api/plane/bgtasks/work_item_link_task.py
+++ b/apps/api/plane/bgtasks/work_item_link_task.py
@@
-def crawl_work_item_link_title(id: str, url: str) -> None:
+def crawl_work_item_link_title(id: str, url: str, expected_updated_at: str | None = None) -> None:
     meta_data = crawl_work_item_link_title_and_favicon(url)
-
-    try:
-        issue_link = IssueLink.objects.get(id=id)
-    except IssueLink.DoesNotExist:
-        logger.warning(f"IssueLink not found for the id {id} and the url {url}")
-        return
-
-    issue_link.metadata = meta_data
-    issue_link.save()
+    filters = {"id": id, "url": url}
+    if expected_updated_at is not None:
+        filters["updated_at"] = expected_updated_at
+    updated = IssueLink.objects.filter(**filters).update(
+        metadata=meta_data,
+        updated_at=timezone.now(),
+    )
+    if not updated:
+        logger.info(f"Skipped stale IssueLink metadata crawl for id {id} and url {url}")
`;
