import type { PlaneCommand } from './lab.ts';

export function exportPlaneRegression(recipe: readonly PlaneCommand[]) {
  const start = recipe.findIndex((command) => command.type === 'start_crawl');
  const finish = recipe.findIndex(
    (command, index) => index > start && command.type === 'release',
  );
  const edit = recipe.find(
    (command, index) =>
      index > start &&
      (finish < 0 || index < finish) &&
      command.type === 'edit_metadata',
  );
  if (start < 0 || finish < 0 || !edit || edit.type !== 'edit_metadata')
    throw new Error(
      'Export needs a queued crawl, a later metadata edit, and worker completion.',
    );
  return `// Generated by Interleave from Plane issue makeplane/plane#9674.
// Pinned source: preview@da1a7ab85012d16836459a10dd92ec55eb739c69.
// Default = proposed compare-and-set patch. Set INTERLEAVE_IMPLEMENTATION=unguarded
// to prove this test catches Plane's current unconditional worker write.
import test from 'node:test';
import assert from 'node:assert/strict';
import { PlaneAdapter, replayPlaneAsync } from '../lib/plane/adapter.ts';

const recipe = ${JSON.stringify(recipe, null, 2)};
const expectedMetadataTitle = ${JSON.stringify(edit.title)};
const mode = process.env.INTERLEAVE_IMPLEMENTATION === 'unguarded'
  ? 'unguarded'
  : 'guarded';

test('a queued Plane crawl cannot overwrite a newer explicit metadata edit', async () => {
  const adapter = new PlaneAdapter(mode);
  try {
    const result = await replayPlaneAsync(recipe, adapter);
    assert.equal(result.assertion?.passed, true,
      result.assertion?.message ?? 'The preservation rule was not evaluated.');
    assert.equal(result.document.link.metadata.title, expectedMetadataTitle);
  } finally {
    adapter.dispose();
  }
});
`;
}

export const PLANE_UPSTREAM_PATCH = `diff --git a/apps/api/plane/app/views/issue/link.py b/apps/api/plane/app/views/issue/link.py
--- a/apps/api/plane/app/views/issue/link.py
+++ b/apps/api/plane/app/views/issue/link.py
@@
-            crawl_work_item_link_title.delay(serializer.data.get("id"), serializer.data.get("url"))
+            crawl_work_item_link_title.delay(
+                serializer.data.get("id"),
+                serializer.data.get("url"),
+                serializer.instance.updated_at.isoformat(),
+            )
@@
-            serializer.save()
-            crawl_work_item_link_title.delay(serializer.data.get("id"), serializer.data.get("url"))
+            url_changed = "url" in serializer.validated_data and serializer.validated_data["url"] != issue_link.url
+            metadata_supplied = "metadata" in serializer.validated_data
+            serializer.save()
+            if url_changed and not metadata_supplied:
+                crawl_work_item_link_title.delay(
+                    serializer.data.get("id"),
+                    serializer.data.get("url"),
+                    serializer.instance.updated_at.isoformat(),
+                )
diff --git a/apps/api/plane/bgtasks/work_item_link_task.py b/apps/api/plane/bgtasks/work_item_link_task.py
--- a/apps/api/plane/bgtasks/work_item_link_task.py
+++ b/apps/api/plane/bgtasks/work_item_link_task.py
@@
-def crawl_work_item_link_title(id: str, url: str) -> None:
+def crawl_work_item_link_title(id: str, url: str, expected_updated_at: str | None = None) -> None:
     meta_data = crawl_work_item_link_title_and_favicon(url)
-
-    try:
-        issue_link = IssueLink.objects.get(id=id)
-    except IssueLink.DoesNotExist:
-        logger.warning(f"IssueLink not found for the id {id} and the url {url}")
-        return
-
-    issue_link.metadata = meta_data
-    issue_link.save()
+    filters = {"id": id, "url": url}
+    if expected_updated_at is not None:
+        filters["updated_at"] = expected_updated_at
+    updated = IssueLink.objects.filter(**filters).update(
+        metadata=meta_data,
+        updated_at=timezone.now(),
+    )
+    if not updated:
+        logger.info(f"Skipped stale IssueLink metadata crawl for id {id} and url {url}")
`;
