// Generated by Interleave from a recorded TodoMVC session.
// Default = patched guard (passes). Set INTERLEAVE_IMPLEMENTATION=unguarded to prove this test catches the old integration.
import test from 'node:test';
import assert from 'node:assert/strict';
import { TodoAdapter } from '../lib/todomvc/adapter.ts';
import { replayTodoAsync } from '../lib/todomvc/adapter.ts';

const recipe = [
  {
    type: 'observe',
  },
  {
    type: 'start_clear',
  },
  {
    type: 'add',
    title: 'Human follow-up',
  },
  {
    type: 'observe',
  },
  {
    type: 'release',
  },
];
const expectedTitle = 'Human follow-up';
const mode =
  process.env.INTERLEAVE_IMPLEMENTATION === 'unguarded'
    ? 'unguarded'
    : 'guarded';

test('a delayed clear preserves todos added after its read', async () => {
  const adapter = new TodoAdapter(mode);
  try {
    await replayTodoAsync(recipe, adapter);
    const afterConflict = adapter.lab.getSnapshot();
    assert.equal(
      afterConflict.assertion?.passed,
      true,
      afterConflict.assertion?.message ??
        'The preservation rule was not evaluated.',
    );
    assert.ok(
      afterConflict.document.todos.some((todo) => todo.title === expectedTitle),
      'The todo added during the delayed operation must survive.',
    );

    if (afterConflict.assertion?.completion === 'blocked') {
      const retry = adapter.clear(500, 'replay');
      adapter.operation.completeNow();
      await retry;
    }
    const recovered = adapter.lab.getSnapshot();
    assert.equal(recovered.document.phase, 'applied');
    assert.ok(
      recovered.document.todos.some((todo) => todo.title === expectedTitle),
    );
    assert.ok(recovered.document.todos.every((todo) => !todo.completed));
  } finally {
    adapter.dispose();
  }
});
