import type { TodoCommand } from './lab.ts';

export function exportTodoRegression(recipe: readonly TodoCommand[]) {
  const start = recipe.findIndex((command) => command.type === 'start_clear');
  const finish = recipe.findIndex(
    (command, index) => index > start && command.type === 'release',
  );
  const expectedTitle = recipe.find(
    (command, index) =>
      index > start && (finish < 0 || index < finish) && command.type === 'add',
  );
  if (start < 0 || finish < 0 || !expectedTitle || expectedTitle.type !== 'add')
    throw new Error(
      'Export needs a delayed clear, a concurrent todo addition, and completion.',
    );
  return `// Generated by Interleave from a recorded TodoMVC session.
// Default = patched guard (passes). Set INTERLEAVE_IMPLEMENTATION=unguarded to prove this test catches the old integration.
import test from 'node:test';
import assert from 'node:assert/strict';
import { TodoAdapter } from '../lib/todomvc/adapter.ts';
import { replayTodoAsync } from '../lib/todomvc/adapter.ts';

const recipe = ${JSON.stringify(recipe, null, 2)};
const expectedTitle = ${JSON.stringify(expectedTitle.title)};
const mode = process.env.INTERLEAVE_IMPLEMENTATION === 'unguarded'
  ? 'unguarded'
  : 'guarded';

test('a delayed clear preserves todos added after its read', async () => {
  const adapter = new TodoAdapter(mode);
  try {
    await replayTodoAsync(recipe, adapter);
    const afterConflict = adapter.lab.getSnapshot();
    assert.equal(afterConflict.assertion?.passed, true,
      afterConflict.assertion?.message ?? 'The preservation rule was not evaluated.');
    assert.ok(afterConflict.document.todos.some((todo) => todo.title === expectedTitle),
      'The todo added during the delayed operation must survive.');

    if (afterConflict.assertion?.completion === 'blocked') {
      const retry = adapter.clear(500, 'replay');
      adapter.operation.completeNow();
      await retry;
    }
    const recovered = adapter.lab.getSnapshot();
    assert.equal(recovered.document.phase, 'applied');
    assert.ok(recovered.document.todos.some((todo) => todo.title === expectedTitle));
    assert.ok(recovered.document.todos.every((todo) => !todo.completed));
  } finally {
    adapter.dispose();
  }
});
`;
}
